import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUi } from "./provider";
import { CounterStoreProvider } from "./store/store-provider";
import Header from "./components/header.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUi>
          <CounterStoreProvider>
            <Header></Header>
            {children}
          </CounterStoreProvider>
        </NextUi>
      </body>
    </html>
  );
}
